dist: xenial
language: java

matrix:
  include:
    - jdk: openjdk11
      env:
      - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw"
    - jdk: openjdk11
      env:
      - _JAVA_OPTIONS="-Dtestfx.robot=awt"

before_install: cd xylixlike

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
